language: java
jdk:
  - openjdk8

# Git Push할 Branch
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r iknotest00 *
  - mkdir -p deploy
  - mv iknotest00.zip deploy/iknotest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: iknotest00-build #s3버킷명
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip파일 접근을 private로
    local_dir: deploy #해당위치의 파일만 s3로 전송
    wait-until-deployed: true


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - dlrsh741@gmail.com

